<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Authorize Device — LODISv2</title>
    @vite(['resources/css/app.css', 'resources/js/app.js', 'resources/js/auth.js'])
</head>
<body class="bg-slate-50 font-sans antialiased text-slate-900 min-h-screen flex items-center justify-center p-6">
    <div class="w-full max-w-md bg-white rounded-3xl border border-slate-200/80 p-8 shadow-xl space-y-6">
        
        <!-- Header -->
        <div class="text-center space-y-2">
            <h2 class="text-xl font-extrabold text-slate-900">
                @if ($method === 'sms')
                    Confirm Mobile Number
                @elseif ($method === 'authenticator')
                    Authenticator App Code
                @else
                    Workstation Verification
                @endif
            </h2>
            <p class="text-xs text-slate-500">
                @if ($method === 'sms')
                    Enter the mobile phone number registered to your employee profile.
                @elseif ($method === 'authenticator')
                    Enter the 6-digit code generated by your Authenticator app.
                @else
                    We sent a 6-digit OTP code to <strong class="text-slate-800">{{ $email }}</strong>.
                @endif
            </p>
        </div>

        @if (session('status'))
            <div class="p-4 rounded-2xl bg-emerald-50 border border-emerald-200 text-xs text-emerald-800">
                {{ session('status') }}
            </div>
        @endif

        @if ($errors->any())
            <div class="p-4 rounded-2xl bg-rose-50 border border-rose-200 text-xs text-rose-700">
                {{ $errors->first() }}
            </div>
        @endif

        <!-- Method Switcher -->
        <div class="flex items-center justify-center gap-2 p-1 bg-slate-100 rounded-2xl text-xs font-bold">
            <form method="POST" action="{{ route('device.otp.switch') }}" class="w-full flex gap-1">
                @csrf
                <button type="submit" name="method" value="email" class="flex-1 py-1.5 rounded-xl transition {{ $method === 'email' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800' }}">
                    Email
                </button>
                @if ($hasSms)
                    <button type="submit" name="method" value="sms" class="flex-1 py-1.5 rounded-xl transition {{ $method === 'sms' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800' }}">
                        SMS
                    </button>
                @endif
                @if ($hasAuthenticator)
                    <button type="submit" name="method" value="authenticator" class="flex-1 py-1.5 rounded-xl transition {{ $method === 'authenticator' ? 'bg-white text-slate-900 shadow-sm' : 'text-slate-500 hover:text-slate-800' }}">
                        2FA App
                    </button>
                @endif
            </form>
        </div>

        <!-- Dynamic Form -->
        <form method="POST" action="{{ route('device.otp.verify') }}" class="space-y-4">
            @csrf
            <div>
                <label for="otp" class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">
                    @if ($method === 'sms')
                        Registered Contact Number
                    @elseif ($method === 'authenticator')
                        6-Digit 2FA Code
                    @else
                        6-Digit OTP Code
                    @endif
                </label>

                @if ($method === 'sms')
                    <input id="otp" type="tel" name="otp" required autofocus class="w-full text-center text-lg font-mono px-4 py-3.5 rounded-2xl border border-slate-200 focus:border-brand focus:ring-4 focus:ring-brand/15 outline-none font-semibold" placeholder="09171234567">
                @else
                    <input id="otp" type="text" name="otp" maxlength="6" required autofocus class="w-full text-center text-2xl font-mono tracking-widest px-4 py-3.5 rounded-2xl border border-slate-200 focus:border-brand focus:ring-4 focus:ring-brand/15 outline-none font-semibold" placeholder="000000">
                @endif
            </div>

            <button type="submit" class="w-full py-3.5 rounded-2xl bg-brand hover:bg-brand-hover text-white text-xs font-bold shadow-md transition">
                Authorize Workstation & Sign In
            </button>
        </form>

        <!-- Resend Link (Email only) -->
        @if ($method === 'email')
            <div class="text-center pt-2">
                <form method="POST" action="{{ route('device.otp.resend') }}">
                    @csrf
                    <button type="submit" class="text-xs font-bold text-brand hover:underline">
                        Didn't receive code? Resend Email OTP
                    </button>
                </form>
            </div>
        @endif

        @if ($authId)
            <div class="text-center">
                <a href="{{ route('device.wait', $authId) }}" class="text-xs font-semibold text-slate-400 hover:text-slate-600">
                    &larr; Return to Device Wait Screen
                </a>
            </div>
        @endif

    </div>
</body>
</html>