<!DOCTYPE html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}" class="h-full bg-slate-50">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>Authenticator 2FA - LODISv2</title>

    <link rel="shortcut icon" href="{{ asset('favicon.ico') }}?v={{ time() }}">
    <link rel="apple-touch-icon" href="{{ asset('images/LODISv2.png') }}">
    <meta name="theme-color" content="#00687A">
    <link rel="manifest" href="{{ asset('manifest.json') }}">

    <link rel="preconnect" href="https://fonts.bunny.net">
    <link href="https://fonts.bunny.net/css?family=inter:400,500,600,700&display=swap" rel="stylesheet" />

    @vite(['resources/css/app.css', 'resources/js/app.js'])
</head>
<body class="min-h-screen font-sans antialiased bg-slate-50 text-slate-900 relative selection:bg-brand selection:text-white">

    <div class="min-h-screen flex flex-col lg:flex-row">

        <!-- Verification Form Panel -->
        <div class="order-1 lg:order-2 lg:w-1/2 flex items-center justify-center p-6 sm:p-10 lg:p-16 bg-white relative">
            <div id="auth-container" class="w-full max-w-md transition-all duration-200">

                <div class="lg:hidden text-center mb-8">
                    <img src="{{ asset('images/LODISv2.png') }}" alt="LODISv2" class="h-12 w-auto mx-auto mb-3 object-contain">
                    <p class="text-[11px] font-bold text-brand uppercase tracking-widest">Lendell Digital Ecosystem</p>
                </div>

                <div class="mb-8 text-center lg:text-left">
                    <h3 class="text-2xl sm:text-3xl font-extrabold text-slate-900 tracking-tight">Authenticator Code</h3>
                    <p class="text-xs sm:text-sm text-slate-500 mt-1" id="form-description">
                        Enter the 6-digit passcode generated by your mobile Authenticator app (e.g. Google Authenticator, Authy).
                    </p>
                </div>

                @if ($errors->any())
                    <div class="mb-6 p-4 rounded-2xl bg-rose-50 border border-rose-200/80 text-xs text-rose-700 shadow-sm">
                        <ul class="list-disc list-inside space-y-1 font-medium">
                            @foreach ($errors->all() as $error)
                                <li>{{ $error }}</li>
                            @endforeach
                        </ul>
                    </div>
                @endif

                <form id="authenticator-form" method="POST" action="{{ route('2fa.authenticator.verify') }}" autocomplete="off" class="space-y-6 transition-opacity duration-200">
                    @csrf

                    <!-- Dynamic Input field toggling between TOTP and Emergency Recovery Code -->
                    <div id="code-input-group">
                        <label for="code" id="code-label" class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2 text-center lg:text-left">6-Digit Passcode</label>
                        <div class="relative rounded-2xl shadow-sm">
                            <input id="code" type="text" name="code" required autofocus maxlength="6" pattern="[0-9]*" inputmode="numeric" autocomplete="one-time-code"
                                class="form-input block w-full py-4 px-4 rounded-2xl border-slate-200 focus:border-brand focus:ring-4 focus:ring-brand/15 text-center font-mono text-2xl tracking-[0.4em] outline-none transition placeholder:text-slate-300 placeholder:tracking-normal"
                                placeholder="000000">
                        </div>
                    </div>

                    <div id="recovery-input-group" class="hidden">
                        <label for="recovery_code" class="block text-xs font-bold text-slate-700 uppercase tracking-wider mb-2">Emergency Recovery Code</label>
                        <div class="relative rounded-2xl shadow-sm">
                            <input id="recovery_code" type="text" name="recovery_code" disabled autocomplete="off"
                                class="form-input block w-full py-3.5 px-4 rounded-2xl border-slate-200 focus:border-brand focus:ring-4 focus:ring-brand/15 font-mono text-sm tracking-widest outline-none transition uppercase placeholder:text-slate-400 placeholder:normal-case"
                                placeholder="XXXXX-XXXXX">
                        </div>
                    </div>

                    <button id="submit-btn" type="submit" disabled
                        class="w-full py-3.5 px-4 rounded-2xl bg-brand hover:bg-brand-hover active:bg-brand-hover text-white text-sm font-bold shadow-lg shadow-brand/20 hover:shadow-xl hover:shadow-brand/30 transition duration-200 ease-in-out flex items-center justify-center gap-2 disabled:opacity-50 disabled:cursor-not-allowed">
                        <svg id="btn-spinner" class="hidden animate-spin h-4 w-4 text-white shrink-0" fill="none" viewBox="0 0 24 24">
                            <circle class="opacity-25" cx="12" cy="12" r="10" stroke="currentColor" stroke-width="4"></circle>
                            <path class="opacity-75" fill="currentColor" d="M4 12a8 8 0 018-8V0C5.373 0 0 5.373 0 12h4zm2 5.291A7.962 7.962 0 014 12H0c0 3.042 1.135 5.824 3 7.938l3-2.647z"></path>
                        </svg>
                        <span id="btn-label">Authenticate Session</span>
                    </button>
                </form>

                <div class="mt-8 pt-6 border-t border-slate-100 text-center space-y-3">
                    <button type="button" id="toggle-recovery-btn" class="text-xs font-bold text-brand hover:text-brand-hover transition">
                        Use an emergency recovery code
                    </button>

                    <div>
                        <form method="POST" action="{{ route('logout') }}">
                            @csrf
                            <button type="submit" class="text-xs font-bold text-slate-400 hover:text-slate-600 transition">
                                Sign out of session
                            </button>
                        </form>
                    </div>
                </div>

            </div>
        </div>

        <!-- Branding Panel -->
        <div class="order-2 lg:order-1 lg:w-1/2 bg-gradient-to-br from-brand-light via-slate-50 to-brand-light/50 border-t lg:border-t-0 lg:border-r border-slate-200/80 p-6 sm:p-10 lg:p-16 flex flex-col justify-between relative overflow-hidden">
            <div class="absolute -top-12 -left-12 w-64 h-64 bg-brand/10 rounded-full blur-3xl pointer-events-none"></div>
            <div class="absolute -bottom-12 -right-12 w-64 h-64 bg-brand/10 rounded-full blur-3xl pointer-events-none"></div>

            <div class="relative z-10">
                <div class="hidden lg:block mb-12">
                    <img src="{{ asset('images/LODISv2.png') }}" alt="LODISv2" class="h-16 lg:h-20 w-auto object-contain">
                </div>

                <div class="max-w-md my-auto">
                    <span class="inline-flex items-center gap-2 px-3.5 py-1.5 rounded-full text-xs font-bold bg-white text-brand border border-slate-200/80 shadow-sm mb-6">
                        <span class="h-2 w-2 rounded-full bg-emerald-500 animate-pulse"></span>
                        Time-Based OTP (TOTP)
                    </span>
                    <h2 class="text-2xl sm:text-3xl lg:text-4xl font-extrabold text-slate-900 tracking-tight leading-tight mb-4">
                        Multi-Factor Identity Validation
                    </h2>
                    <p class="text-slate-600 text-xs sm:text-sm leading-relaxed mb-8">
                        LODISv2 enforces multi-factor authentication for elevated account security across all internal enterprise services.
                    </p>
                </div>
            </div>

            <div class="mt-8 sm:mt-12 pt-6 border-t border-slate-200/60 text-xs text-slate-500 flex justify-between items-center relative z-10 font-medium">
                <span>&copy; {{ date('Y') }} Lendell Outsourcing Solutions, Inc. All rights reserved.</span>
                <span class="font-mono text-slate-400">v2.1.0</span>
            </div>
        </div>

    </div>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            const codeInput = document.getElementById('code');
            const recoveryInput = document.getElementById('recovery_code');
            const submitBtn = document.getElementById('submit-btn');
            const form = document.getElementById('authenticator-form');
            const btnSpinner = document.getElementById('btn-spinner');
            const btnLabel = document.getElementById('btn-label');
            const toggleRecoveryBtn = document.getElementById('toggle-recovery-btn');
            const codeGroup = document.getElementById('code-input-group');
            const recoveryGroup = document.getElementById('recovery-input-group');
            const formDescription = document.getElementById('form-description');

            let isUsingRecovery = false;

            codeInput?.addEventListener('input', (e) => {
                if (!isUsingRecovery) {
                    e.target.value = e.target.value.replace(/[^0-9]/g, '');
                    submitBtn.disabled = e.target.value.length !== 6;
                    if (e.target.value.length === 6) {
                        form.requestSubmit();
                    }
                }
            });

            recoveryInput?.addEventListener('input', (e) => {
                if (isUsingRecovery) {
                    submitBtn.disabled = e.target.value.trim().length === 0;
                }
            });

            toggleRecoveryBtn?.addEventListener('click', () => {
                isUsingRecovery = !isUsingRecovery;

                if (isUsingRecovery) {
                    codeGroup.classList.add('hidden');
                    codeInput.disabled = true;

                    recoveryGroup.classList.remove('hidden');
                    recoveryInput.disabled = false;
                    recoveryInput.focus();

                    formDescription.textContent = 'Enter one of your pre-generated emergency backup recovery codes.';
                    toggleRecoveryBtn.textContent = 'Use 6-digit authenticator passcode';
                    submitBtn.disabled = recoveryInput.value.trim().length === 0;
                } else {
                    recoveryGroup.classList.add('hidden');
                    recoveryInput.disabled = true;

                    codeGroup.classList.remove('hidden');
                    codeInput.disabled = false;
                    codeInput.focus();

                    formDescription.textContent = 'Enter the 6-digit passcode generated by your mobile Authenticator app (e.g. Google Authenticator, Authy).';
                    toggleRecoveryBtn.textContent = 'Use an emergency recovery code';
                    submitBtn.disabled = codeInput.value.length !== 6;
                }
            });

            form?.addEventListener('submit', () => {
                submitBtn.disabled = true;
                btnSpinner.classList.remove('hidden');
                btnLabel.textContent = 'Validating Passcode...';
            });
        });
    </script>
</body>
</html>